version: "3.1"

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=gitpod
      - N8N_BASIC_AUTH_PASSWORD=gitpod123
      - GENERIC_TIMEZONE=America/Vancouver
    volumes:
      - ./data/n8n:/home/node/.n8n
